import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from "next/link";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      <body className="antialiased">
        <div className="hero-gradient" />
        <header className="sticky top-0 z-50 w-full border-b border-white/10 bg-black/50 backdrop-blur-md">
          <nav className="container flex h-16 items-center justify-between">
            <Link href="/" className="text-xl font-bold tracking-tight text-white hover:opacity-80 transition-opacity">
              AI<span className="text-purple-500">Blog</span>
            </Link>
            
            <div className="flex gap-8 items-center">
              <Link href="/AllBlogsPage" className="nav-link">Explore</Link>
              <Link href="/CreateBlogByMCP" className="nav-link">AI Creator</Link>
              <Link href="/LoginPage" className="nav-link">Login</Link>
              <Link href="/CreateNewAccount" className="bg-white text-black px-4 py-2 rounded-full text-sm font-semibold hover:bg-white/90 transition-all">
                Get Started
              </Link>
            </div>
          </nav>
        </header>

        <main className="container py-12">
          {children}
        </main>
        
        <footer className="container py-12 border-t border-white/10 text-center text-sm text-gray-500">
          © 2026 AI Blog Generator • Built with MCP & Gemini
        </footer>
      </body>
    </html>
  );
}
